# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CatalogProduct(BaseModel):
    """
    CatalogProduct
    """ # noqa: E501
    external_id: StrictStr = Field(description="The store's product id, e.g. gid://shopify/Product/1")
    title: StrictStr
    handle: Optional[StrictStr] = None
    product_type: Optional[StrictStr] = None
    vendor: Optional[StrictStr] = None
    tags: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    collections: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = None
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["external_id", "title", "handle", "product_type", "vendor", "tags", "collections", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CatalogProduct from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CatalogProduct from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_id": obj.get("external_id"),
            "title": obj.get("title"),
            "handle": obj.get("handle"),
            "product_type": obj.get("product_type"),
            "vendor": obj.get("vendor"),
            "tags": obj.get("tags"),
            "collections": obj.get("collections"),
            "url": obj.get("url")
        })
        return _obj


