# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.56.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.citation_match_mode import CitationMatchMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompetitorCreateResponseCompetitor(BaseModel):
    """
    CompetitorCreateResponseCompetitor
    """ # noqa: E501
    id: StrictInt
    brand_name: StrictStr
    domain: StrictStr
    citation_match_mode: CitationMatchMode
    citation_match_path: Optional[StrictStr] = Field(description="Set only when citation_match_mode is path_prefix")
    color: Optional[StrictStr]
    matching_names: List[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "brand_name", "domain", "citation_match_mode", "citation_match_path", "color", "matching_names"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompetitorCreateResponseCompetitor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if citation_match_path (nullable) is None
        # and model_fields_set contains the field
        if self.citation_match_path is None and "citation_match_path" in self.model_fields_set:
            _dict['citation_match_path'] = None

        # set to None if color (nullable) is None
        # and model_fields_set contains the field
        if self.color is None and "color" in self.model_fields_set:
            _dict['color'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompetitorCreateResponseCompetitor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "brand_name": obj.get("brand_name"),
            "domain": obj.get("domain"),
            "citation_match_mode": obj.get("citation_match_mode"),
            "citation_match_path": obj.get("citation_match_path"),
            "color": obj.get("color"),
            "matching_names": obj.get("matching_names")
        })
        return _obj


