# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.competitor_create_response_competitor import CompetitorCreateResponseCompetitor
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompetitorCreateResponse(BaseModel):
    """
    CompetitorCreateResponse
    """ # noqa: E501
    project_id: StrictInt
    competitor: CompetitorCreateResponseCompetitor
    competitors_remaining: Optional[StrictInt] = Field(description="Competitors the plan still allows in this project; null when unlimited")
    total_competitors: StrictInt
    request_id: StrictStr
    __properties: ClassVar[List[str]] = ["project_id", "competitor", "competitors_remaining", "total_competitors", "request_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompetitorCreateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of competitor
        if self.competitor:
            _dict['competitor'] = self.competitor.to_dict()
        # set to None if competitors_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.competitors_remaining is None and "competitors_remaining" in self.model_fields_set:
            _dict['competitors_remaining'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompetitorCreateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "competitor": CompetitorCreateResponseCompetitor.from_dict(obj["competitor"]) if obj.get("competitor") is not None else None,
            "competitors_remaining": obj.get("competitors_remaining"),
            "total_competitors": obj.get("total_competitors"),
            "request_id": obj.get("request_id")
        })
        return _obj


