# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from llmpulse.models.geo_audit_comparison_changes_inner import GeoAuditComparisonChangesInner
from llmpulse.models.geo_audit_run import GeoAuditRun
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GeoAuditComparison(BaseModel):
    """
    GeoAuditComparison
    """ # noqa: E501
    project_id: Optional[StrictInt] = None
    from_run: Optional[GeoAuditRun] = None
    to_run: Optional[GeoAuditRun] = None
    comparable: Optional[StrictBool] = None
    score_delta: Optional[Union[StrictFloat, StrictInt]] = None
    metric_deltas: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = None
    counts: Optional[Dict[str, StrictInt]] = None
    changes: Optional[List[GeoAuditComparisonChangesInner]] = None
    request_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["project_id", "from_run", "to_run", "comparable", "score_delta", "metric_deltas", "counts", "changes", "request_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeoAuditComparison from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_run
        if self.from_run:
            _dict['from_run'] = self.from_run.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_run
        if self.to_run:
            _dict['to_run'] = self.to_run.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item_changes in self.changes:
                if _item_changes:
                    _items.append(_item_changes.to_dict())
            _dict['changes'] = _items
        # set to None if from_run (nullable) is None
        # and model_fields_set contains the field
        if self.from_run is None and "from_run" in self.model_fields_set:
            _dict['from_run'] = None

        # set to None if to_run (nullable) is None
        # and model_fields_set contains the field
        if self.to_run is None and "to_run" in self.model_fields_set:
            _dict['to_run'] = None

        # set to None if score_delta (nullable) is None
        # and model_fields_set contains the field
        if self.score_delta is None and "score_delta" in self.model_fields_set:
            _dict['score_delta'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeoAuditComparison from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "from_run": GeoAuditRun.from_dict(obj["from_run"]) if obj.get("from_run") is not None else None,
            "to_run": GeoAuditRun.from_dict(obj["to_run"]) if obj.get("to_run") is not None else None,
            "comparable": obj.get("comparable"),
            "score_delta": obj.get("score_delta"),
            "metric_deltas": obj.get("metric_deltas"),
            "counts": obj.get("counts"),
            "changes": [GeoAuditComparisonChangesInner.from_dict(_item) for _item in obj["changes"]] if obj.get("changes") is not None else None,
            "request_id": obj.get("request_id")
        })
        return _obj


