# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.56.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.geo_alert_events_inner import GeoAlertEventsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GeoAlert(BaseModel):
    """
    GeoAlert
    """ # noqa: E501
    id: Optional[StrictInt] = None
    audit_id: Optional[StrictStr] = None
    audit_type: Optional[StrictStr] = None
    target: Optional[StrictStr] = None
    run_sequence: Optional[StrictInt] = None
    severity: Optional[StrictStr] = None
    events: Optional[List[GeoAlertEventsInner]] = None
    created_at: Optional[datetime] = None
    app_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "audit_id", "audit_type", "target", "run_sequence", "severity", "events", "created_at", "app_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeoAlert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeoAlert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "audit_id": obj.get("audit_id"),
            "audit_type": obj.get("audit_type"),
            "target": obj.get("target"),
            "run_sequence": obj.get("run_sequence"),
            "severity": obj.get("severity"),
            "events": [GeoAlertEventsInner.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "created_at": obj.get("created_at"),
            "app_url": obj.get("app_url")
        })
        return _obj


