# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from llmpulse.models.intelligence_task_product import IntelligenceTaskProduct
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntelligenceTaskCreateRequest(BaseModel):
    """
    IntelligenceTaskCreateRequest
    """ # noqa: E501
    project_id: StrictInt
    task_type: StrictStr = Field(description="product_listing is API-only: it needs product and returns ready-to-apply product page copy")
    prompt_id: Optional[StrictInt] = Field(default=None, description="Not used by product_listing; send null or omit it")
    custom_topic: Optional[StrictStr] = None
    user_instructions: Optional[StrictStr] = None
    output_language_code: Optional[StrictStr] = None
    existing_content: Optional[StrictStr] = None
    existing_content_url: Optional[StrictStr] = None
    product: Optional[IntelligenceTaskProduct] = None
    prompt_ids: Optional[Annotated[List[StrictInt], Field(max_length=20)]] = Field(default=None, description="product_listing only: up to 20 project prompts the copy should answer")
    __properties: ClassVar[List[str]] = ["project_id", "task_type", "prompt_id", "custom_topic", "user_instructions", "output_language_code", "existing_content", "existing_content_url", "product", "prompt_ids"]

    @field_validator('task_type')
    def task_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['brief', 'create', 'update', 'pr_insights', 'custom', 'product_listing']):
            raise ValueError("must be one of enum values ('brief', 'create', 'update', 'pr_insights', 'custom', 'product_listing')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntelligenceTaskCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        # set to None if prompt_id (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_id is None and "prompt_id" in self.model_fields_set:
            _dict['prompt_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntelligenceTaskCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "task_type": obj.get("task_type"),
            "prompt_id": obj.get("prompt_id"),
            "custom_topic": obj.get("custom_topic"),
            "user_instructions": obj.get("user_instructions"),
            "output_language_code": obj.get("output_language_code"),
            "existing_content": obj.get("existing_content"),
            "existing_content_url": obj.get("existing_content_url"),
            "product": IntelligenceTaskProduct.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "prompt_ids": obj.get("prompt_ids")
        })
        return _obj


