# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.52.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from llmpulse.models.llms_txt_technical_geo_report_result_data import LlmsTxtTechnicalGeoReportResultData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LlmsTxtTechnicalGeoReport(BaseModel):
    """
    An llms_txt technical GEO report with its files, in the shape GET /technical_geo_reports/{id} returns
    """ # noqa: E501
    id: Optional[StrictInt] = None
    report_type: Optional[StrictStr] = Field(default=None, description="Always llms_txt")
    project_id: Optional[StrictInt] = None
    batch_id: Optional[StrictInt] = Field(default=None, description="Bundle the report was created in; null for a report created on its own")
    url: Optional[StrictStr] = Field(default=None, description="Always null for llms_txt reports; domain names the website")
    domain: Optional[StrictStr] = None
    country_code: Optional[StrictStr] = None
    output_language_code: Optional[StrictStr] = Field(default=None, description="ISO 639-1 code the files were requested in; null when they are written in the website's own language")
    status: Optional[StrictStr] = None
    result_available: Optional[StrictBool] = None
    overall_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Always null for llms_txt reports")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    result_data: Optional[LlmsTxtTechnicalGeoReportResultData] = None
    error_message: Optional[StrictStr] = None
    poll_after_seconds: Optional[StrictInt] = Field(default=None, description="Seconds to wait before polling again while the report runs; null once it has finished")
    app_url: Optional[StrictStr] = Field(default=None, description="Opens this report in the app")
    request_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "report_type", "project_id", "batch_id", "url", "domain", "country_code", "output_language_code", "status", "result_available", "overall_score", "created_at", "updated_at", "result_data", "error_message", "poll_after_seconds", "app_url", "request_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LlmsTxtTechnicalGeoReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result_data
        if self.result_data:
            _dict['result_data'] = self.result_data.to_dict()
        # set to None if batch_id (nullable) is None
        # and model_fields_set contains the field
        if self.batch_id is None and "batch_id" in self.model_fields_set:
            _dict['batch_id'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if country_code (nullable) is None
        # and model_fields_set contains the field
        if self.country_code is None and "country_code" in self.model_fields_set:
            _dict['country_code'] = None

        # set to None if output_language_code (nullable) is None
        # and model_fields_set contains the field
        if self.output_language_code is None and "output_language_code" in self.model_fields_set:
            _dict['output_language_code'] = None

        # set to None if overall_score (nullable) is None
        # and model_fields_set contains the field
        if self.overall_score is None and "overall_score" in self.model_fields_set:
            _dict['overall_score'] = None

        # set to None if result_data (nullable) is None
        # and model_fields_set contains the field
        if self.result_data is None and "result_data" in self.model_fields_set:
            _dict['result_data'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if poll_after_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.poll_after_seconds is None and "poll_after_seconds" in self.model_fields_set:
            _dict['poll_after_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LlmsTxtTechnicalGeoReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "report_type": obj.get("report_type"),
            "project_id": obj.get("project_id"),
            "batch_id": obj.get("batch_id"),
            "url": obj.get("url"),
            "domain": obj.get("domain"),
            "country_code": obj.get("country_code"),
            "output_language_code": obj.get("output_language_code"),
            "status": obj.get("status"),
            "result_available": obj.get("result_available"),
            "overall_score": obj.get("overall_score"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "result_data": LlmsTxtTechnicalGeoReportResultData.from_dict(obj["result_data"]) if obj.get("result_data") is not None else None,
            "error_message": obj.get("error_message"),
            "poll_after_seconds": obj.get("poll_after_seconds"),
            "app_url": obj.get("app_url"),
            "request_id": obj.get("request_id")
        })
        return _obj


