# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.48.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.project_details_all_of_stats import ProjectDetailsAllOfStats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectDetails(BaseModel):
    """
    ProjectDetails
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = Field(default=None, description="Internal project label (sidebar, settings, admin)")
    brand_name: Optional[StrictStr] = Field(default=None, description="LLM-facing brand label (used in prompts and customer-facing charts). Defaults to `name` when not set.")
    url: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    matching_names: Optional[List[StrictStr]] = None
    industry: Optional[StrictStr] = None
    business_model: Optional[StrictStr] = None
    business_model_other: Optional[StrictStr] = Field(default=None, description="Set only when business_model is OTHER")
    primary_products: Optional[List[StrictStr]] = None
    target_audience: Optional[StrictStr] = None
    brand_voice: Optional[StrictStr] = None
    goals: Optional[StrictStr] = None
    country_code: Optional[StrictStr] = None
    language_code: Optional[StrictStr] = None
    paused: Optional[StrictBool] = None
    google_play_id: Optional[StrictStr] = None
    app_store_id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    stats: Optional[ProjectDetailsAllOfStats] = None
    __properties: ClassVar[List[str]] = ["id", "name", "brand_name", "url", "description", "matching_names", "industry", "business_model", "business_model_other", "primary_products", "target_audience", "brand_voice", "goals", "country_code", "language_code", "paused", "google_play_id", "app_store_id", "created_at", "stats"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        # set to None if business_model_other (nullable) is None
        # and model_fields_set contains the field
        if self.business_model_other is None and "business_model_other" in self.model_fields_set:
            _dict['business_model_other'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "brand_name": obj.get("brand_name"),
            "url": obj.get("url"),
            "description": obj.get("description"),
            "matching_names": obj.get("matching_names"),
            "industry": obj.get("industry"),
            "business_model": obj.get("business_model"),
            "business_model_other": obj.get("business_model_other"),
            "primary_products": obj.get("primary_products"),
            "target_audience": obj.get("target_audience"),
            "brand_voice": obj.get("brand_voice"),
            "goals": obj.get("goals"),
            "country_code": obj.get("country_code"),
            "language_code": obj.get("language_code"),
            "paused": obj.get("paused"),
            "google_play_id": obj.get("google_play_id"),
            "app_store_id": obj.get("app_store_id"),
            "created_at": obj.get("created_at"),
            "stats": ProjectDetailsAllOfStats.from_dict(obj["stats"]) if obj.get("stats") is not None else None
        })
        return _obj


