# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.49.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectCreateRequestOwnedMedia(BaseModel):
    """
    Requires Growth plan or above
    """ # noqa: E501
    youtube_channel_url: Optional[StrictStr] = None
    instagram_profile_url: Optional[StrictStr] = None
    facebook_page_url: Optional[StrictStr] = None
    tiktok_profile_url: Optional[StrictStr] = None
    app_store_url: Optional[StrictStr] = None
    google_play_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["youtube_channel_url", "instagram_profile_url", "facebook_page_url", "tiktok_profile_url", "app_store_url", "google_play_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectCreateRequestOwnedMedia from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectCreateRequestOwnedMedia from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "youtube_channel_url": obj.get("youtube_channel_url"),
            "instagram_profile_url": obj.get("instagram_profile_url"),
            "facebook_page_url": obj.get("facebook_page_url"),
            "tiktok_profile_url": obj.get("tiktok_profile_url"),
            "app_store_url": obj.get("app_store_url"),
            "google_play_url": obj.get("google_play_url")
        })
        return _obj


