# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.56.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectCreateResponseLimits(BaseModel):
    """
    ProjectCreateResponseLimits
    """ # noqa: E501
    projects_remaining: Optional[StrictInt] = None
    prompts_available: Optional[StrictInt] = None
    competitors_remaining: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["projects_remaining", "prompts_available", "competitors_remaining"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectCreateResponseLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if projects_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.projects_remaining is None and "projects_remaining" in self.model_fields_set:
            _dict['projects_remaining'] = None

        # set to None if prompts_available (nullable) is None
        # and model_fields_set contains the field
        if self.prompts_available is None and "prompts_available" in self.model_fields_set:
            _dict['prompts_available'] = None

        # set to None if competitors_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.competitors_remaining is None and "competitors_remaining" in self.model_fields_set:
            _dict['competitors_remaining'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectCreateResponseLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "projects_remaining": obj.get("projects_remaining"),
            "prompts_available": obj.get("prompts_available"),
            "competitors_remaining": obj.get("competitors_remaining")
        })
        return _obj


