# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.project_details_all_of_stats_prompts_by_brand_kind import ProjectDetailsAllOfStatsPromptsByBrandKind
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectDetailsAllOfStats(BaseModel):
    """
    ProjectDetailsAllOfStats
    """ # noqa: E501
    prompts_count: Optional[StrictInt] = None
    prompts_by_brand_kind: Optional[ProjectDetailsAllOfStatsPromptsByBrandKind] = None
    competitors_count: Optional[StrictInt] = None
    collections_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["prompts_count", "prompts_by_brand_kind", "competitors_count", "collections_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectDetailsAllOfStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of prompts_by_brand_kind
        if self.prompts_by_brand_kind:
            _dict['prompts_by_brand_kind'] = self.prompts_by_brand_kind.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectDetailsAllOfStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prompts_count": obj.get("prompts_count"),
            "prompts_by_brand_kind": ProjectDetailsAllOfStatsPromptsByBrandKind.from_dict(obj["prompts_by_brand_kind"]) if obj.get("prompts_by_brand_kind") is not None else None,
            "competitors_count": obj.get("competitors_count"),
            "collections_count": obj.get("collections_count")
        })
        return _obj


