# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.56.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from llmpulse.models.tag_ref import TagRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromptRecord(BaseModel):
    """
    PromptRecord
    """ # noqa: E501
    id: StrictInt
    prompt_text: StrictStr
    collection_id: Optional[StrictInt] = Field(description="Primary tag, when the prompt has one")
    collection_ids: List[StrictInt] = Field(description="Every tag the prompt belongs to")
    tags: List[TagRef]
    country_code: Optional[StrictStr]
    language_code: Optional[StrictStr]
    prompt_type: Optional[StrictStr] = Field(description="Search intent: informational, navigational, commercial or transactional. Null until the prompt is classified")
    brand_kind: Optional[StrictStr] = Field(description="Brand focus: brand, brand_other or non_brand. Null until the prompt is classified")
    last_executed_at: Optional[datetime] = Field(description="Null until the prompt has run")
    app_url: StrictStr = Field(description="Opens this prompt in the app. The link names its project, so it opens there for any user with access to that project")
    __properties: ClassVar[List[str]] = ["id", "prompt_text", "collection_id", "collection_ids", "tags", "country_code", "language_code", "prompt_type", "brand_kind", "last_executed_at", "app_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromptRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # set to None if collection_id (nullable) is None
        # and model_fields_set contains the field
        if self.collection_id is None and "collection_id" in self.model_fields_set:
            _dict['collection_id'] = None

        # set to None if country_code (nullable) is None
        # and model_fields_set contains the field
        if self.country_code is None and "country_code" in self.model_fields_set:
            _dict['country_code'] = None

        # set to None if language_code (nullable) is None
        # and model_fields_set contains the field
        if self.language_code is None and "language_code" in self.model_fields_set:
            _dict['language_code'] = None

        # set to None if prompt_type (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_type is None and "prompt_type" in self.model_fields_set:
            _dict['prompt_type'] = None

        # set to None if brand_kind (nullable) is None
        # and model_fields_set contains the field
        if self.brand_kind is None and "brand_kind" in self.model_fields_set:
            _dict['brand_kind'] = None

        # set to None if last_executed_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_executed_at is None and "last_executed_at" in self.model_fields_set:
            _dict['last_executed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromptRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "prompt_text": obj.get("prompt_text"),
            "collection_id": obj.get("collection_id"),
            "collection_ids": obj.get("collection_ids"),
            "tags": [TagRef.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "country_code": obj.get("country_code"),
            "language_code": obj.get("language_code"),
            "prompt_type": obj.get("prompt_type"),
            "brand_kind": obj.get("brand_kind"),
            "last_executed_at": obj.get("last_executed_at"),
            "app_url": obj.get("app_url")
        })
        return _obj


