# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.48.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from llmpulse.models.actor import Actor
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SovResponseCurrentInner(BaseModel):
    """
    SovResponseCurrentInner
    """ # noqa: E501
    actor: Optional[Actor] = None
    share: Optional[Union[StrictFloat, StrictInt]] = None
    previous_share: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The actor's share in the last complete bucket before the current one; null without complete history.")
    avg_share: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mean share across complete buckets with data (partial buckets excluded); null without complete history.")
    __properties: ClassVar[List[str]] = ["actor", "share", "previous_share", "avg_share"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SovResponseCurrentInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of actor
        if self.actor:
            _dict['actor'] = self.actor.to_dict()
        # set to None if previous_share (nullable) is None
        # and model_fields_set contains the field
        if self.previous_share is None and "previous_share" in self.model_fields_set:
            _dict['previous_share'] = None

        # set to None if avg_share (nullable) is None
        # and model_fields_set contains the field
        if self.avg_share is None and "avg_share" in self.model_fields_set:
            _dict['avg_share'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SovResponseCurrentInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actor": Actor.from_dict(obj["actor"]) if obj.get("actor") is not None else None,
            "share": obj.get("share"),
            "previous_share": obj.get("previous_share"),
            "avg_share": obj.get("avg_share")
        })
        return _obj


