# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.22.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateProjectDraftRequest(BaseModel):
    """
    UpdateProjectDraftRequest
    """ # noqa: E501
    step: StrictStr
    name: Optional[StrictStr] = None
    brand_name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    industry: Optional[List[StrictStr]] = None
    matching_names: Optional[List[StrictStr]] = None
    external_identifier: Optional[StrictStr] = None
    prompts: Optional[Annotated[List[StrictStr], Field(max_length=100)]] = None
    competitors: Optional[List[Dict[str, Any]]] = None
    youtube_channel_url: Optional[StrictStr] = None
    instagram_profile_url: Optional[StrictStr] = None
    facebook_page_url: Optional[StrictStr] = None
    tiktok_profile_url: Optional[StrictStr] = None
    app_store_url: Optional[StrictStr] = None
    google_play_url: Optional[StrictStr] = None
    suggest: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["step", "name", "brand_name", "description", "industry", "matching_names", "external_identifier", "prompts", "competitors", "youtube_channel_url", "instagram_profile_url", "facebook_page_url", "tiktok_profile_url", "app_store_url", "google_play_url", "suggest"]

    @field_validator('step')
    def step_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['details', 'prompts', 'competitors', 'owned_media']):
            raise ValueError("must be one of enum values ('details', 'prompts', 'competitors', 'owned_media')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateProjectDraftRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateProjectDraftRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "step": obj.get("step"),
            "name": obj.get("name"),
            "brand_name": obj.get("brand_name"),
            "description": obj.get("description"),
            "industry": obj.get("industry"),
            "matching_names": obj.get("matching_names"),
            "external_identifier": obj.get("external_identifier"),
            "prompts": obj.get("prompts"),
            "competitors": obj.get("competitors"),
            "youtube_channel_url": obj.get("youtube_channel_url"),
            "instagram_profile_url": obj.get("instagram_profile_url"),
            "facebook_page_url": obj.get("facebook_page_url"),
            "tiktok_profile_url": obj.get("tiktok_profile_url"),
            "app_store_url": obj.get("app_store_url"),
            "google_play_url": obj.get("google_play_url"),
            "suggest": obj.get("suggest") if obj.get("suggest") is not None else True
        })
        return _obj


