# coding: utf-8

"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.57.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WebAnalyticsSchemaResponse(BaseModel):
    """
    WebAnalyticsSchemaResponse
    """ # noqa: E501
    project_id: Optional[StrictInt] = None
    provider: Optional[StrictStr] = Field(default=None, description="The connected web analytics provider.")
    var_property: Optional[StrictStr] = Field(default=None, description="The property, site, report suite (rsid:...), data view (dataview:...) or project every query runs on.", alias="property")
    query_language: Optional[StrictStr] = Field(default=None, description="The native query format the provider accepts.")
    docs_url: Optional[StrictStr] = Field(default=None, description="The provider's reference for that format.")
    allowed_fields: Optional[List[StrictStr]] = Field(default=None, description="Top-level query fields that are forwarded.")
    rules: Optional[List[StrictStr]] = Field(default=None, description="What the bridge enforces and the provider's main constraints.")
    example: Optional[Dict[str, Any]] = Field(default=None, description="A worked query to adapt.")
    fields: Optional[Dict[str, Any]] = Field(default=None, description="The provider's live field list where it offers one: GA4 dimensions and metrics with custom definitions, Adobe ids, Matomo report methods, PostHog event names, the Plausible catalog. Null when the provider did not return it.")
    fields_unavailable: Optional[StrictStr] = Field(default=None, description="Present when the field list could not be read; the format and example still apply.")
    request_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["project_id", "provider", "property", "query_language", "docs_url", "allowed_fields", "rules", "example", "fields", "fields_unavailable", "request_id"]

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['google_analytics', 'adobe_analytics', 'matomo', 'posthog', 'plausible', 'piano']):
            raise ValueError("must be one of enum values ('google_analytics', 'adobe_analytics', 'matomo', 'posthog', 'plausible', 'piano')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebAnalyticsSchemaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fields (nullable) is None
        # and model_fields_set contains the field
        if self.fields is None and "fields" in self.model_fields_set:
            _dict['fields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebAnalyticsSchemaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "provider": obj.get("provider"),
            "property": obj.get("property"),
            "query_language": obj.get("query_language"),
            "docs_url": obj.get("docs_url"),
            "allowed_fields": obj.get("allowed_fields"),
            "rules": obj.get("rules"),
            "example": obj.get("example"),
            "fields": obj.get("fields"),
            "fields_unavailable": obj.get("fields_unavailable"),
            "request_id": obj.get("request_id")
        })
        return _obj


