"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.51.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from llmpulse.models.answer_details import AnswerDetails

from llmpulse.api_client import ApiClient, RequestSerialized
from llmpulse.api_response import ApiResponse
from llmpulse.rest import RESTResponseType


class AnswersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_answer(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        id: StrictInt,
        include_source_page_details: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AnswerDetails:
        """Get one AI response

        Full answer with mentions, citations, sentiments, sources, shopping_products, brand_entities, fan_out_queries. Pass `include_source_page_details=true` to nest page-cache metadata under each source.

        :param project_id: Project ID (required)
        :type project_id: int
        :param id: (required)
        :type id: int
        :param include_source_page_details:
        :type include_source_page_details: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_answer_serialize(
            project_id=project_id,
            id=id,
            include_source_page_details=include_source_page_details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AnswerDetails",
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_answer_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        id: StrictInt,
        include_source_page_details: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AnswerDetails]:
        """Get one AI response

        Full answer with mentions, citations, sentiments, sources, shopping_products, brand_entities, fan_out_queries. Pass `include_source_page_details=true` to nest page-cache metadata under each source.

        :param project_id: Project ID (required)
        :type project_id: int
        :param id: (required)
        :type id: int
        :param include_source_page_details:
        :type include_source_page_details: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_answer_serialize(
            project_id=project_id,
            id=id,
            include_source_page_details=include_source_page_details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AnswerDetails",
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_answer_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        id: StrictInt,
        include_source_page_details: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get one AI response

        Full answer with mentions, citations, sentiments, sources, shopping_products, brand_entities, fan_out_queries. Pass `include_source_page_details=true` to nest page-cache metadata under each source.

        :param project_id: Project ID (required)
        :type project_id: int
        :param id: (required)
        :type id: int
        :param include_source_page_details:
        :type include_source_page_details: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_answer_serialize(
            project_id=project_id,
            id=id,
            include_source_page_details=include_source_page_details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AnswerDetails",
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_answer_serialize(
        self,
        project_id,
        id,
        include_source_page_details,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if include_source_page_details is not None:
            
            _query_params.append(('include_source_page_details', include_source_page_details))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/answers/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_answers(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        mention_filter: Annotated[Optional[StrictStr], Field(description="Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.")] = None,
        citation_filter: Annotated[Optional[StrictStr], Field(description="Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).")] = None,
        competitors: Annotated[Optional[StrictStr], Field(description="Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.")] = None,
        no_result: Annotated[Optional[StrictBool], Field(description="Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """List AI responses

        Successful prompt-execution responses with truncated content (max 10,000 chars). Pass `query` for case-insensitive full-text search inside response texts: `total` becomes the exact count of matching responses and each item returns `snippet` + `match_count` instead of `response`/`response_truncated`.

        :param project_id: Project ID (required)
        :type project_id: int
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param mention_filter: Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.
        :type mention_filter: str
        :param citation_filter: Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).
        :type citation_filter: str
        :param competitors: Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
        :type competitors: str
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param query: Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.
        :type query: str
        :param no_result: Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.
        :type no_result: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_answers_serialize(
            project_id=project_id,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            mention_filter=mention_filter,
            citation_filter=citation_filter,
            competitors=competitors,
            var_from=var_from,
            to=to,
            page=page,
            per_page=per_page,
            query=query,
            no_result=no_result,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_answers_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        mention_filter: Annotated[Optional[StrictStr], Field(description="Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.")] = None,
        citation_filter: Annotated[Optional[StrictStr], Field(description="Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).")] = None,
        competitors: Annotated[Optional[StrictStr], Field(description="Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.")] = None,
        no_result: Annotated[Optional[StrictBool], Field(description="Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """List AI responses

        Successful prompt-execution responses with truncated content (max 10,000 chars). Pass `query` for case-insensitive full-text search inside response texts: `total` becomes the exact count of matching responses and each item returns `snippet` + `match_count` instead of `response`/`response_truncated`.

        :param project_id: Project ID (required)
        :type project_id: int
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param mention_filter: Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.
        :type mention_filter: str
        :param citation_filter: Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).
        :type citation_filter: str
        :param competitors: Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
        :type competitors: str
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param query: Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.
        :type query: str
        :param no_result: Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.
        :type no_result: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_answers_serialize(
            project_id=project_id,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            mention_filter=mention_filter,
            citation_filter=citation_filter,
            competitors=competitors,
            var_from=var_from,
            to=to,
            page=page,
            per_page=per_page,
            query=query,
            no_result=no_result,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_answers_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        mention_filter: Annotated[Optional[StrictStr], Field(description="Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.")] = None,
        citation_filter: Annotated[Optional[StrictStr], Field(description="Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).")] = None,
        competitors: Annotated[Optional[StrictStr], Field(description="Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.")] = None,
        no_result: Annotated[Optional[StrictBool], Field(description="Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List AI responses

        Successful prompt-execution responses with truncated content (max 10,000 chars). Pass `query` for case-insensitive full-text search inside response texts: `total` becomes the exact count of matching responses and each item returns `snippet` + `match_count` instead of `response`/`response_truncated`.

        :param project_id: Project ID (required)
        :type project_id: int
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param mention_filter: Filter by which brands are mentioned, as a two-axis matrix (your brand x competitors): mentions_you / not_mentions_you, mentions_competitor / not_mentions_competitor, and the four combined cells you_and_competitor, competitor_not_you (a rival wins and you are absent), you_not_competitor, no_brands (no tracked brand appears, i.e. open space). Combine with 'competitors' to narrow the competitor side to specific rivals; on a negative cell that reads 'none of these'. On /dimensions/sources it applies to the crawled content of each cited page instead of the answer text. The legacy value 'competitors_only' is still accepted as an alias of competitor_not_you.
        :type mention_filter: str
        :param citation_filter: Same two-axis matrix applied to the domains cited in the answer instead of the brands named in it. Independent of mention_filter; pass both to intersect them (e.g. mentions_you + not_cites_you finds answers that talk about you without linking to you).
        :type citation_filter: str
        :param competitors: Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
        :type competitors: str
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param query: Case-insensitive full-text search inside AI response texts. Switches items to snippet + match_count mode.
        :type query: str
        :param no_result: Filter sentinel non-answers (provider returned nothing after retries; excluded from platform metrics). false = only real answers, true = only sentinels, omit = both. Every item carries its own no_result flag.
        :type no_result: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_answers_serialize(
            project_id=project_id,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            mention_filter=mention_filter,
            citation_filter=citation_filter,
            competitors=competitors,
            var_from=var_from,
            to=to,
            page=page,
            per_page=per_page,
            query=query,
            no_result=no_result,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_answers_serialize(
        self,
        project_id,
        model,
        collection_id,
        country_code,
        language_code,
        prompt,
        mention_filter,
        citation_filter,
        competitors,
        var_from,
        to,
        page,
        per_page,
        query,
        no_result,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if model is not None:
            
            _query_params.append(('model', model))
            
        if collection_id is not None:
            
            _query_params.append(('collection_id', collection_id))
            
        if country_code is not None:
            
            _query_params.append(('country_code', country_code))
            
        if language_code is not None:
            
            _query_params.append(('language_code', language_code))
            
        if prompt is not None:
            
            _query_params.append(('prompt', prompt))
            
        if mention_filter is not None:
            
            _query_params.append(('mention_filter', mention_filter))
            
        if citation_filter is not None:
            
            _query_params.append(('citation_filter', citation_filter))
            
        if competitors is not None:
            
            _query_params.append(('competitors', competitors))
            
        if var_from is not None:
            if isinstance(var_from, datetime):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if query is not None:
            
            _query_params.append(('query', query))
            
        if no_result is not None:
            
            _query_params.append(('no_result', no_result))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/answers',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


