"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.22.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated

from llmpulse.api_client import ApiClient, RequestSerialized
from llmpulse.api_response import ApiResponse
from llmpulse.rest import RESTResponseType


class CitationIntelligenceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_cited_url_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Cited URL cached content


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_content_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_cited_url_content_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Cited URL cached content


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_content_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_cited_url_content_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cited URL cached content


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_content_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_cited_url_content_serialize(
        self,
        project_id,
        url_sha256,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if url_sha256 is not None:
            _path_params['url_sha256'] = url_sha256
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/citation_intelligence/urls/{url_sha256}/content',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_cited_url_detail(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Cited URL detail


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_detail_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_cited_url_detail_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Cited URL detail


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_detail_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_cited_url_detail_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cited URL detail


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cited_url_detail_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_cited_url_detail_serialize(
        self,
        project_id,
        url_sha256,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if url_sha256 is not None:
            _path_params['url_sha256'] = url_sha256
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/citation_intelligence/urls/{url_sha256}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_mentions_by_citing_domain(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        domains: Annotated[List[StrictStr], Field(description="Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Mention share by citing domain

        For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.

        :param project_id: Project ID (required)
        :type project_id: int
        :param domains: Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com (required)
        :type domains: List[str]
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_mentions_by_citing_domain_serialize(
            project_id=project_id,
            domains=domains,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_mentions_by_citing_domain_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        domains: Annotated[List[StrictStr], Field(description="Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Mention share by citing domain

        For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.

        :param project_id: Project ID (required)
        :type project_id: int
        :param domains: Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com (required)
        :type domains: List[str]
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_mentions_by_citing_domain_serialize(
            project_id=project_id,
            domains=domains,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_mentions_by_citing_domain_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        domains: Annotated[List[StrictStr], Field(description="Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com")],
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Mention share by citing domain

        For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.

        :param project_id: Project ID (required)
        :type project_id: int
        :param domains: Source domains to analyze, e.g. domains[]=gmac.com&domains[]=educaweb.com (required)
        :type domains: List[str]
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_mentions_by_citing_domain_serialize(
            project_id=project_id,
            domains=domains,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_mentions_by_citing_domain_serialize(
        self,
        project_id,
        domains,
        model,
        collection_id,
        country_code,
        language_code,
        prompt,
        var_from,
        to,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'domains': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if domains is not None:
            
            _query_params.append(('domains', domains))
            
        if model is not None:
            
            _query_params.append(('model', model))
            
        if collection_id is not None:
            
            _query_params.append(('collection_id', collection_id))
            
        if country_code is not None:
            
            _query_params.append(('country_code', country_code))
            
        if language_code is not None:
            
            _query_params.append(('language_code', language_code))
            
        if prompt is not None:
            
            _query_params.append(('prompt', prompt))
            
        if var_from is not None:
            if isinstance(var_from, datetime):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/citation_intelligence/mentions_by_domain',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_citation_groups(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        view: Optional[StrictStr] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        order: Optional[StrictStr] = None,
        direction: Optional[StrictStr] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        query: Optional[StrictStr] = None,
        source_type: Optional[StrictStr] = None,
        sentiment: Optional[StrictStr] = None,
        content_gap: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Grouped citation intelligence

        Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position=0. Owned and competitor source matching honor the project's exact-subdomain setting. Filter vocabulary aligns with `source_type` returned by the API.

        :param project_id: Project ID (required)
        :type project_id: int
        :param view:
        :type view: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param order:
        :type order: str
        :param direction:
        :type direction: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param query:
        :type query: str
        :param source_type:
        :type source_type: str
        :param sentiment:
        :type sentiment: str
        :param content_gap:
        :type content_gap: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_citation_groups_serialize(
            project_id=project_id,
            view=view,
            page=page,
            per_page=per_page,
            order=order,
            direction=direction,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            query=query,
            source_type=source_type,
            sentiment=sentiment,
            content_gap=content_gap,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_citation_groups_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        view: Optional[StrictStr] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        order: Optional[StrictStr] = None,
        direction: Optional[StrictStr] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        query: Optional[StrictStr] = None,
        source_type: Optional[StrictStr] = None,
        sentiment: Optional[StrictStr] = None,
        content_gap: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Grouped citation intelligence

        Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position=0. Owned and competitor source matching honor the project's exact-subdomain setting. Filter vocabulary aligns with `source_type` returned by the API.

        :param project_id: Project ID (required)
        :type project_id: int
        :param view:
        :type view: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param order:
        :type order: str
        :param direction:
        :type direction: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param query:
        :type query: str
        :param source_type:
        :type source_type: str
        :param sentiment:
        :type sentiment: str
        :param content_gap:
        :type content_gap: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_citation_groups_serialize(
            project_id=project_id,
            view=view,
            page=page,
            per_page=per_page,
            order=order,
            direction=direction,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            query=query,
            source_type=source_type,
            sentiment=sentiment,
            content_gap=content_gap,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_citation_groups_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        view: Optional[StrictStr] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        order: Optional[StrictStr] = None,
        direction: Optional[StrictStr] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Optional[StrictInt] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="ISO country code (e.g. US, GB, DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="ISO language code (e.g. en, es, de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        var_from: Optional[datetime] = None,
        to: Optional[datetime] = None,
        query: Optional[StrictStr] = None,
        source_type: Optional[StrictStr] = None,
        sentiment: Optional[StrictStr] = None,
        content_gap: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Grouped citation intelligence

        Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position=0. Owned and competitor source matching honor the project's exact-subdomain setting. Filter vocabulary aligns with `source_type` returned by the API.

        :param project_id: Project ID (required)
        :type project_id: int
        :param view:
        :type view: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param order:
        :type order: str
        :param direction:
        :type direction: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id:
        :type collection_id: int
        :param country_code: ISO country code (e.g. US, GB, DE)
        :type country_code: str
        :param language_code: ISO language code (e.g. en, es, de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param var_from:
        :type var_from: datetime
        :param to:
        :type to: datetime
        :param query:
        :type query: str
        :param source_type:
        :type source_type: str
        :param sentiment:
        :type sentiment: str
        :param content_gap:
        :type content_gap: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_citation_groups_serialize(
            project_id=project_id,
            view=view,
            page=page,
            per_page=per_page,
            order=order,
            direction=direction,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            var_from=var_from,
            to=to,
            query=query,
            source_type=source_type,
            sentiment=sentiment,
            content_gap=content_gap,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_citation_groups_serialize(
        self,
        project_id,
        view,
        page,
        per_page,
        order,
        direction,
        model,
        collection_id,
        country_code,
        language_code,
        prompt,
        var_from,
        to,
        query,
        source_type,
        sentiment,
        content_gap,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if view is not None:
            
            _query_params.append(('view', view))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if order is not None:
            
            _query_params.append(('order', order))
            
        if direction is not None:
            
            _query_params.append(('direction', direction))
            
        if model is not None:
            
            _query_params.append(('model', model))
            
        if collection_id is not None:
            
            _query_params.append(('collection_id', collection_id))
            
        if country_code is not None:
            
            _query_params.append(('country_code', country_code))
            
        if language_code is not None:
            
            _query_params.append(('language_code', language_code))
            
        if prompt is not None:
            
            _query_params.append(('prompt', prompt))
            
        if var_from is not None:
            if isinstance(var_from, datetime):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if query is not None:
            
            _query_params.append(('query', query))
            
        if source_type is not None:
            
            _query_params.append(('source_type', source_type))
            
        if sentiment is not None:
            
            _query_params.append(('sentiment', sentiment))
            
        if content_gap is not None:
            
            _query_params.append(('content_gap', content_gap))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/citation_intelligence/groups',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_cited_url_occurrences(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Cited URL occurrences


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_cited_url_occurrences_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_cited_url_occurrences_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Cited URL occurrences


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_cited_url_occurrences_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_cited_url_occurrences_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        url_sha256: Annotated[str, Field(strict=True, description="64-character hex SHA-256 of the cited URL")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cited URL occurrences


        :param project_id: Project ID (required)
        :type project_id: int
        :param url_sha256: 64-character hex SHA-256 of the cited URL (required)
        :type url_sha256: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_cited_url_occurrences_serialize(
            project_id=project_id,
            url_sha256=url_sha256,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '404': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_cited_url_occurrences_serialize(
        self,
        project_id,
        url_sha256,
        page,
        per_page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if url_sha256 is not None:
            _path_params['url_sha256'] = url_sha256
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/citation_intelligence/urls/{url_sha256}/occurrences',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


