"""
    LLM Pulse API

    REST API client for LLM Pulse AI visibility analytics.

    The version of the OpenAPI document: 1.51.0
    Contact: info@llmpulse.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated

from llmpulse.api_client import ApiClient, RequestSerialized
from llmpulse.api_response import ApiResponse
from llmpulse.rest import RESTResponseType


class ShoppingAdsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_ads(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per advertising domain, or one per placement")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only placements identified as the tracked brand's own (view=ads)")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.")] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the ad title, domain or snippet")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """List AI ad placements

        Paid placements returned inside AI answers. view=advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view=ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per advertising domain, or one per placement
        :type view: str
        :param owned: Return only placements identified as the tracked brand's own (view=ads)
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction: Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.
        :type direction: str
        :param query: Case-insensitive substring filter on the ad title, domain or snippet
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ads_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_ads_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per advertising domain, or one per placement")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only placements identified as the tracked brand's own (view=ads)")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.")] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the ad title, domain or snippet")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """List AI ad placements

        Paid placements returned inside AI answers. view=advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view=ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per advertising domain, or one per placement
        :type view: str
        :param owned: Return only placements identified as the tracked brand's own (view=ads)
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction: Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.
        :type direction: str
        :param query: Case-insensitive substring filter on the ad title, domain or snippet
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ads_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_ads_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per advertising domain, or one per placement")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only placements identified as the tracked brand's own (view=ads)")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.")] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the ad title, domain or snippet")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List AI ad placements

        Paid placements returned inside AI answers. view=advertisers (default) returns one row per advertising domain with its placement count, prompt reach and average and best position; view=ads returns the individual placements with title, snippet, position and the prompt that triggered them. Position 1 is the best slot, so a LOWER average position is better. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per advertising domain, or one per placement
        :type view: str
        :param owned: Return only placements identified as the tracked brand's own (view=ads)
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction: Sort direction for view=advertisers. Defaults to desc, except avg_position and domain which default to asc.
        :type direction: str
        :param query: Case-insensitive substring filter on the ad title, domain or snippet
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ads_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_ads_serialize(
        self,
        project_id,
        page,
        per_page,
        view,
        owned,
        order,
        direction,
        query,
        model,
        collection_id,
        country_code,
        language_code,
        prompt,
        prompt_type,
        brand_kind,
        range,
        var_from,
        to,
        output,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if view is not None:
            
            _query_params.append(('view', view))
            
        if owned is not None:
            
            _query_params.append(('owned', owned))
            
        if order is not None:
            
            _query_params.append(('order', order))
            
        if direction is not None:
            
            _query_params.append(('direction', direction))
            
        if query is not None:
            
            _query_params.append(('query', query))
            
        if model is not None:
            
            _query_params.append(('model', model))
            
        if collection_id is not None:
            
            _query_params.append(('collection_id', collection_id))
            
        if country_code is not None:
            
            _query_params.append(('country_code', country_code))
            
        if language_code is not None:
            
            _query_params.append(('language_code', language_code))
            
        if prompt is not None:
            
            _query_params.append(('prompt', prompt))
            
        if prompt_type is not None:
            
            _query_params.append(('prompt_type', prompt_type))
            
        if brand_kind is not None:
            
            _query_params.append(('brand_kind', brand_kind))
            
        if range is not None:
            
            _query_params.append(('range', range))
            
        if var_from is not None:
            if isinstance(var_from, datetime):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if output is not None:
            
            _query_params.append(('output', output))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dimensions/ads',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_shopping(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per distinct product, or one per merchant")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Optional[StrictStr] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the product title")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """List shopping results

        Product cards returned inside AI answers. view=products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view=merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per distinct product, or one per merchant
        :type view: str
        :param owned: Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction:
        :type direction: str
        :param query: Case-insensitive substring filter on the product title
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_shopping_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_shopping_with_http_info(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per distinct product, or one per merchant")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Optional[StrictStr] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the product title")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """List shopping results

        Product cards returned inside AI answers. view=products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view=merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per distinct product, or one per merchant
        :type view: str
        :param owned: Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction:
        :type direction: str
        :param query: Case-insensitive substring filter on the product title
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_shopping_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_shopping_without_preload_content(
        self,
        project_id: Annotated[StrictInt, Field(description="Project ID")],
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        view: Annotated[Optional[StrictStr], Field(description="Row shape: one per distinct product, or one per merchant")] = None,
        owned: Annotated[Optional[StrictBool], Field(description="Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Sort field; the allowed set depends on view")] = None,
        direction: Optional[StrictStr] = None,
        query: Annotated[Optional[StrictStr], Field(description="Case-insensitive substring filter on the product title")] = None,
        model: Annotated[Optional[StrictStr], Field(description="Filter by AI model. Models the API key's user has not enabled are silently dropped.")] = None,
        collection_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.")] = None,
        country_code: Annotated[Optional[StrictStr], Field(description="One ISO country code or a comma-separated list (e.g. US,GB,DE)")] = None,
        language_code: Annotated[Optional[StrictStr], Field(description="One ISO language code or a comma-separated list (e.g. en,es,de)")] = None,
        prompt: Annotated[Optional[StrictInt], Field(description="Filter by prompt ID")] = None,
        prompt_type: Annotated[Optional[StrictStr], Field(description="One prompt type or a comma-separated list: informational, navigational, commercial, transactional")] = None,
        brand_kind: Annotated[Optional[StrictStr], Field(description="Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.")] = None,
        range: Annotated[Optional[StrictInt], Field(description="Number of days to look back (alternative to from/to)")] = None,
        var_from: Optional[datetime] = None,
        to: Annotated[Optional[datetime], Field(description="End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.")] = None,
        output: Annotated[Optional[StrictStr], Field(description="Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List shopping results

        Product cards returned inside AI answers. view=products (default) returns one row per distinct product, merged across executions, with its appearance count, price range, rating and whether it is yours, plus a currency_count saying how many currencies it was priced in (above 1 means the row reports its highest-priced listing and min_price may be another currency); view=merchants returns one row per selling merchant, with a currency field naming the money its price range and average are expressed in (providers price each market in its own currency, so a merchant that sells in more than one reports the currency most of its prices use). Every response also carries a totals block matching the KPI cards in the app, whose avg_price is computed inside the single currency named by avg_price_currency. Requires the Scale plan or above.

        :param project_id: Project ID (required)
        :type project_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param view: Row shape: one per distinct product, or one per merchant
        :type view: str
        :param owned: Return only products identified as the tracked brand's own. On view=merchants this narrows to the merchants selling those products; the totals block stays account-wide.
        :type owned: bool
        :param order: Sort field; the allowed set depends on view
        :type order: str
        :param direction:
        :type direction: str
        :param query: Case-insensitive substring filter on the product title
        :type query: str
        :param model: Filter by AI model. Models the API key's user has not enabled are silently dropped.
        :type model: str
        :param collection_id: One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
        :type collection_id: str
        :param country_code: One ISO country code or a comma-separated list (e.g. US,GB,DE)
        :type country_code: str
        :param language_code: One ISO language code or a comma-separated list (e.g. en,es,de)
        :type language_code: str
        :param prompt: Filter by prompt ID
        :type prompt: int
        :param prompt_type: One prompt type or a comma-separated list: informational, navigational, commercial, transactional
        :type prompt_type: str
        :param brand_kind: Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default.
        :type brand_kind: str
        :param range: Number of days to look back (alternative to from/to)
        :type range: int
        :param var_from:
        :type var_from: datetime
        :param to: End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
        :type to: datetime
        :param output: Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. 'flat' returns the same metadata plus 'columns' and 'rows'; 'csv' returns those rows as text/csv. Errors are always returned as JSON.
        :type output: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_shopping_serialize(
            project_id=project_id,
            page=page,
            per_page=per_page,
            view=view,
            owned=owned,
            order=order,
            direction=direction,
            query=query,
            model=model,
            collection_id=collection_id,
            country_code=country_code,
            language_code=language_code,
            prompt=prompt,
            prompt_type=prompt_type,
            brand_kind=brand_kind,
            range=range,
            var_from=var_from,
            to=to,
            output=output,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '422': "ApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_shopping_serialize(
        self,
        project_id,
        page,
        per_page,
        view,
        owned,
        order,
        direction,
        query,
        model,
        collection_id,
        country_code,
        language_code,
        prompt,
        prompt_type,
        brand_kind,
        range,
        var_from,
        to,
        output,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if project_id is not None:
            
            _query_params.append(('project_id', project_id))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if view is not None:
            
            _query_params.append(('view', view))
            
        if owned is not None:
            
            _query_params.append(('owned', owned))
            
        if order is not None:
            
            _query_params.append(('order', order))
            
        if direction is not None:
            
            _query_params.append(('direction', direction))
            
        if query is not None:
            
            _query_params.append(('query', query))
            
        if model is not None:
            
            _query_params.append(('model', model))
            
        if collection_id is not None:
            
            _query_params.append(('collection_id', collection_id))
            
        if country_code is not None:
            
            _query_params.append(('country_code', country_code))
            
        if language_code is not None:
            
            _query_params.append(('language_code', language_code))
            
        if prompt is not None:
            
            _query_params.append(('prompt', prompt))
            
        if prompt_type is not None:
            
            _query_params.append(('prompt_type', prompt_type))
            
        if brand_kind is not None:
            
            _query_params.append(('brand_kind', brand_kind))
            
        if range is not None:
            
            _query_params.append(('range', range))
            
        if var_from is not None:
            if isinstance(var_from, datetime):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if output is not None:
            
            _query_params.append(('output', output))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dimensions/shopping',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


